[package]
name = "rolodex-starter"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.87"

[lib]
crate-type = ["cdylib"]

[features]
default = ["codec-h264"]
codec-h264 = ["rolodex-core/codec-h264", "rolodex-worker/codec-h264"]
codec-h265 = ["rolodex-core/codec-h265", "rolodex-worker/codec-h265"]

[dependencies]
rolodex-core = { git = "https://github.com/conservationtv/rolodex.git", rev = "0fd517008e530e739ed165bdecedb71679fba5f3", default-features = false }
rolodex-worker = { git = "https://github.com/conservationtv/rolodex.git", rev = "0fd517008e530e739ed165bdecedb71679fba5f3", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"
